[package]
name = "advent_of_code2021"
version = "0.1.0"
authors = ["Fredrik Jansson <frjansso@cisco.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
nom = {version = "7", features = []}
nom-regex = "0.2.0"
regex = "1"
